services:
  python:
    build: 
      context: python
      target: production
    restart: unless-stopped
    environment:
      - S3_URL=${S3_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - PUBLIC_S3_URL=${PUBLIC_S3_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:4000/ || exit 1" ]
      start_period: 5s

  frontend:
    build: 
      context: frontend
      target: production
    environment:
      - VITE_KEYCLOAK_URL=${KEYCLOAK_URL}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/ || exit 1" ]
      start_period: 5s

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    ports:
      - 80:80
    